### ISSUE TITLE
Search By Building

### ISSUE THREAD

**Issue by ghost** [ryanhugh/searchneu#60]
Nothing more fanciful than an addition to the searching algorithm. This would be very reasonable for students who prioritize location on campus.

E.g., "West Village" matches "West Village A [...], West Village H 212" in any order.

This appears doable with https://github.com/ryanhugh/searchneu/blob/b6e852877b5b0e7449f30c1d377b7ef0b8f5010d/common/search.js#L54

**Comment by ryanhugh** [comment]
Would you be looking to have different buildings on campus appear as individual results? Eg. being able to search through buildings and have them appear as cards, much like classes and employees do now?

Right now the only data that is in the database is classes and employees. We could totally add another data set for all the buildings on campus (and there are actually some great places we could pull the data from!) LMK if you are interested in working on this. :)

The line you found there keeps track of which building each class is in. If we enable that and then type in “west village”, all he classes in west village appear. I had enabled for a little bit, but then disabled it because it wasn’t clear why those classes were appearing.

**Comment by ryanhugh** [comment]
Closing as dup of #12
